### ISSUE TITLE
Detection differs between Linux and Windows

### ISSUE THREAD

**Issue by ceving** [DediProgSW/SF100Linux#15]
We used DediProg Eng on Windows. When I run "Detect" on Windows, I get the message, that the chip can not be detected exactly and the Windows tool shows me two alternatives. For example:

- W25Q64DW
- W25Q64FW

I have to use the W25Q64FW.

When I do the same with the Linux command line tool, it shows only the DW version:

    $ sudo ./dpcmd -d
    
    DpCmd Linux 1.11.1.07 Engine Version:
    Last Built on May 25 2018
    
     
    
    Device 1 (SF600001):    detecting chip
    By reading the chip ID, the chip applies to [ W25Q64DW ]
    W25Q64DW chip size is 8388608 bytes.

And the W25Q64DW is wrong, because I have to use the W25Q64FW.

**Comment by ceving** [comment]
This

https://github.com/DediProgSW/SF100Linux/blob/master/dpcmd.c#L697

seems to me, that only the first match is reported.

**Comment by DediprogEvy** [comment]
Hi,

Please update the code, this issue has been modified. software will show all the chip type name which has same chip id. But the order of chip type names are follow by database order. So we recommend user use --type command to assign chip.
  
DediProg Evy
