### ISSUE TITLE
Linux SF100 does not detect Winbond 25Q512JVFQ chip

### ISSUE THREAD

**Issue by AlpusChen** [DediProgSW/SF100Linux#18]
Linux SF100 does not detect Winbond 25Q512JVFQ chip, but Windows SF100 program can detect. Please help to update linux program.

**Comment by AlpusChen** [comment]
[root@alpus SF100Linux-master]# ./dpcmd -d

DpCmd Linux 1.11.1.07 Engine Version:
Last Built on May 25 2018

Device 1 (DP014942):    detecting chip
Error: chip not identified.

**Comment by rajanikanth009** [comment]
I am also facing this issue kindly share the solution for this detect chip issue?

**Comment by quadpixels** [comment]
I ran into the same problem, and I created a Pull Request with the changes I made to support this chip: https://github.com/DediProgSW/SF100Linux/pull/22

**Comment by DediprogEvy** [comment]
Hi all,

Sorry for late reply.
Please update code to check if still have problem. 
I've try to program chip W25Q512JV-IQ and Erase, Program, Verify all pass.
I'll close this issue, if still have problem, please let me know. 
Thank you.

BR,
DediProg Evy

**Comment by DediprogEvy** [comment]
[root@fedora27 SF100Linux]# ./dpcmd --type W25Q512JV-IQ -e -p /home/eliu/Downloads/64mbyte.bin -v

DpCmd Linux 1.11.4.03 Engine Version:
Last Built on May 25 2018

 
Chip Type W25Q512JV-IQ is applied manually.
W25Q512JV-IQ chip size is 67108864 bytes.


Erasing, please wait ... 

Device 1 (SF700003):
178.6s elapsed

Device 1 (SF700003):
Erase OK

Loading file, please wait ...(/home/eliu/Downloads/64mbyte.bin)

Programming, please wait ...

Device 1 (SF700003):
474.6s elapsed

Device 1 (SF700003):
Program OK

Checksum(whole file): 36512FD4
Checksum(Written part of file): 36512FD4

Verifying, please wait ...
Device 1 (SF700003):
241.5s elapsed

Device 1 (SF700003):
Verify OK
