### ISSUE TITLE
Lack of Documentation/Dependencies

### ISSUE THREAD

**Issue by ThorPilcher** [DediProgSW/SF100Linux#21]
This project needs a README.MD with the dependency requirements to `make` the project.
It looks like I'm missing at least one package beyond build-essential, I need to know all the others I may or may not be missing.

**Comment by klderos** [comment]
klderos@klderos-dev:~/gitrepos/DediProgSW_SF100Linux$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
klderos@klderos-dev:~/gitrepos/DediProgSW_SF100Linux$ sudo apt install libusb-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libusb-dev is already the newest version (2:0.1.12-31).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
klderos@klderos-dev:~/gitrepos/DediProgSW_SF100Linux$ make
Package libusb-1.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libusb-1.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libusb-1.0' found
  CC  dpcmd.o
In file included from dpcmd.c:7:0:
usbdriver.h:6:10: fatal error: libusb.h: No such file or directory
 #include <libusb.h>
          ^~~~~~~~~~
compilation terminated.
Makefile:43: recipe for target 'dpcmd.o' failed
make: *** [dpcmd.o] Error 1

**Comment by DediprogEvy** [comment]
Hi ThorPilcher,

I noticed that you use "sudo apt install libusb-dev" to install USB driver, please try again by using "sudo apt-get install libusb-dev". 

Thanks.
DediProg Evy

**Comment by tjaalton** [comment]
'apt install' is a valid command for installing software

what's missing is that 'libusb.h' is not in libusb-dev, but in libusb-1.0-0-dev, and you also need pkg-config installed as well

**Comment by jacobmgn** [comment]
This can be resolved by specifying the correct location.

```
diff --git a/usbdriver.h b/usbdriver.h
index 72e00ff..e5862d4 100755
--- a/usbdriver.h
+++ b/usbdriver.h
@@ -3,7 +3,7 @@
 #ifndef DEDI_USB_DRIVER
 #define DEDI_USB_DRIVER

-#include <libusb.h>
+#include <libusb-1.0/libusb.h>
 #include <stdbool.h>
 #include <stdio.h>
 #include <string.h>
```
