### ISSUE TITLE
W25Q128BV program fail issue

### ISSUE THREAD

**Issue by yuyexingkong** [DediProgSW/SF100Linux#23]
DpCmd Linux 1.11.2.01 Engine Version:
Last Built on May 25 2018

 
By reading the chip ID, the chip applies to [ W25Q128BV ]
W25Q128BV parameters to be applied by default
W25Q128BV chip size is 16777216 bytes.

Loading file, please wait ...(LICENSE)
Auto Sequences, please wait ...
Device 1 (DP106264):
Warning: Failed to detect flash (0).
0.299534	 s elapsed

Device 1 (DP106264):
Error: Automatic program Failed

**Comment by DediprogEvy** [comment]
Hi yuyexingkong,

The code has been update, please let me know if still have problem.

Thanks,
DediProg Evy
