### ISSUE TITLE
W25Q256FV program failed

### ISSUE THREAD

**Issue by yuyexingkong** [DediProgSW/SF100Linux#24]
DpCmd Linux 1.11.2.01 Engine Version:
Last Built on May 25 2018

 
By reading the chip ID, the chip applies to [ W25Q256FV ]
W25Q256FV parameters to be applied by default
W25Q256FV chip size is 33554432 bytes.

Loading file, please wait ...(LICENSE)
Auto Sequences, please wait ...
Device 1 (DP106264):
Warning: Failed to detect flash (0).
0.291188	 s elapsed

Device 1 (DP106264):
Error: Automatic program Failed

**Comment by yuyexingkong** [comment]
windows dpcmd tool program ok

**Comment by zhouchuanfu** [comment]
My question is the same as yours.

**Comment by muthuselvamr** [comment]
any answer for this thread ?

**Comment by zhouchuanfu** [comment]
> 
> 
> any answer for this thread ?

Use "dpcmd -T <flash type> " point a flash type just OK.

**Comment by zhouchuanfu** [comment]
oh, but can't use of read function.

**Comment by DediprogEvy** [comment]
Hi all,

Please update code. I've tried to erase/program/verify chip W25Q256FV pass.
Thank you.
 
DediProg Evy.


Following is my test.

[root@fedora27 SF100Linux]# ./dpcmd --type W25Q256FV -e -p /home/eliu/Downloads/32Mbyte.bin -v

DpCmd Linux 1.11.4.03 Engine Version:
Last Built on May 25 2018

 
Chip Type W25Q256FV is applied manually.
W25Q256FV chip size is 33554432 bytes.


Erasing, please wait ... 

Device 1 (SF700003):
72.9s elapsed

Device 1 (SF700003):
Erase OK

Loading file, please wait ...(/home/eliu/Downloads/32Mbyte.bin)

Programming, please wait ...

Device 1 (SF700003):
247.7s elapsed

Device 1 (SF700003):
Program OK

Checksum(whole file): 4D1F65FF
Checksum(Written part of file): 4D1F65FF

Verifying, please wait ...
Device 1 (SF700003):
124.6s elapsed

Device 1 (SF700003):
Verify OK
