### ISSUE TITLE
Missing support for flash chip W25R256JVEQ in Linux version

### ISSUE THREAD

**Issue by johann-pfefferl** [DediProgSW/SF100Linux#29]
Windows version seems to have support for this device type.
![20200916_145358](https://user-images.githubusercontent.com/13101007/93340537-37b44800-f82d-11ea-989f-29b6dfcbfed9.jpg)

**Comment by reinauer** [comment]
You can use the Windows (6.x) version of ChipInfoDb.dedicfg (convert it from UTF16 to UTF8, eg. with dos2unix)

**Comment by reinauer** [comment]
Latest version should support the chip... Please try and close this issue if appropriate

**Comment by Benwang217** [comment]
Already supported
