### ISSUE TITLE
License specification required

### ISSUE THREAD

**Issue by jan-kiszka** [DediProgSW/SF100Linux#3]
Please specify under which license this code is distributed. Without any, no one allowed to use it, strictly spoken.

**Comment by Benwang217** [comment]
Do you mean you would like to have a license to pull the source code?

**Comment by jan-kiszka** [comment]
I mean, in most legal systems on this planet, you do need a license in order to use a copyright protected work like yours. It's not a matter of "like to", rather "have to".

**Comment by styyle14** [comment]
Bump. This is should be considered a top priority. If this project is actually open source, it is crucial that you state as such. As-is, this project cannot be legally forked in most countries. You can change this setting in Github or add the declaration to a README file. Note you can check http://choosealicense.com/ for help deciding on a license to use.

Thanks!

**Comment by DediprogEvy** [comment]
License has been added. Thanks for your reminder.
