### ISSUE TITLE
SPI command "06" ( Write Enable )  to W25Q256FV returns 97 bytes

### ISSUE THREAD

**Issue by AntonioSanta** [DediProgSW/SF100Linux#30]
Hello,
I am trying writing to Flash status register through SF100 to W25Q256FV flash memory chip.
There is a write enable command to send first , command is 06 and it is not expecting to return an answer. 
So I am sending :
sudo ./dpcmd --raw-instruction "06" 

DpCmd Linux 1.11.2.01 Engine Version:
Last Built on May 25 2018

 
By reading the chip ID, the chip applies to [ W25Q256FV ]
W25Q256FV parameters to be applied by default
W25Q256FV chip size is 33554432 bytes.

Device 1:
issuing raw instruction "0x06" returns 97 bytes as required:
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 01 00 01 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
SR=0x00

I don't understand why it returns 97 bytes, is this correct ? We were thinking this was just a raw-instruction command so no bytes to return.
We are following procedure to increase output driver strength by issuing sequence : 
1) "06" : Write Enable
2) "11 val", to write the value output driver strength , where val is the byte in hex of the driver strength wanted ( 00 -> 100% )
3) "15" with sudo ./dpcmd --raw-instruction "15" --raw-require-return 1 to read back the final value just written.

thank you

**Comment by DediprogEvy** [comment]
Hi AntonioSanta,

The code has been updated, please check if still have problem. Thank you.

The following is my test.

root@evy-virtual-machine:/home/evy/Documents/SF100Linux# ./dpcmd --type W25Q256FV --raw-instruction 06

DpCmd Linux 1.11.4.03 Engine Version:
Last Build on May 25 2018

Chip Type W25Q256FV is applied manually
W25Q256FV chip size is 33554432 bytes.

Device 1:
SR=0x02


BR,
DediProg Evy
