### ISSUE TITLE
Feature: Need to add DpCmd --device-SN to specify the serial number function of the programmer in Linux DpCmd version

### ISSUE THREAD

**Issue by muthuselvamr** [DediProgSW/SF100Linux#34]
Hello,

In Windows DpCmd version 7.2.0.17, a new feature has been added that "DpCmd --device-SN" directly specify the serial number function of the programmer. The same  needs to be included in Linux Dpcmd version.

Thanks,
Muthu.

**Comment by Benwang217** [comment]
Hi Muthu,

We are developing the feature and will be released as soon as possible.

Thanks,
Ben

**Comment by DediprogEvy** [comment]
Hi Muthu,

The code has been updated. Please update and let us know if there's any problem.

Thanks.
DediProg Evy
