### ISSUE TITLE
Flash fails with Error: Operation Timed out

### ISSUE THREAD

**Issue by muthuselvamr** [DediProgSW/SF100Linux#38]
Hi All,

This is the first time I am trying to do dediprog flashing using linux dpcmd. I am getting below error always with any chip. I am not sure what missing here. Can some one help me out on this ?

_sudo ./dpcmd --auto /remote/tmp/WC_ICXOutImage_NM.bin --verify

DpCmd Linux 1.11.3.03 Engine Version:
Last Built on May 25 2018

By reading the chip ID, the chip applies to [ MX25L25635F ]
MX25L25635F parameters to be applied by default
MX25L25635F chip size is 33554432 bytes.

Loading file, please wait ...(/remote/tmp/WC_ICXOutImage_NM.bin)
Auto Sequences, please wait ...
Device 1 (SF618507):
30.5s elapsed**Error: Operation timed out**
60.7s elapsed**Error: Operation timed out**_

**Comment by solonfan** [comment]
I meet same error

**Comment by muthuselvamr** [comment]
Do any one have any update on this thread... I didn't flash a chip successfully yet with linux tool.

**Comment by solonfan** [comment]
I mailed to dediprog  team,no update also.

**Comment by reinauer** [comment]
@solonfan Did you try to flash the same chip?
@muthuselvamr What Linux distro are you using? Wha HW/FW revision is your SF100?

**Comment by solonfan** [comment]
@reinauer Yes,same chip.Winbond25Q256JVFQ

**Comment by muthuselvamr** [comment]
@reinauer I am using SF600. Please find the details below.

**Linux Details:**
Distributor ID: LinuxMint
Description:    Linux Mint 19.3 Tricia
Release:        19.3
Codename:       tricia

**Hardware details:**
Type: SF600
FW version: 7.2.49
FPGA Version: 0x100E
HW version: 2.2
IO Mode: Single IO

CHIP Type: MX25L51245G

**Comment by muthuselvamr** [comment]
@reinauer Hi... Do you have any comment towards solution ?

**Comment by tammerOfTheGods** [comment]
@solonfan @muthuselvamr - please post what libusb version you have installed on the host (dpkg -l libusb*)

dpcmd works with 
```
dpkg -l libusb*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                       Version                    Architecture               Description
+++-==========================================-==========================-==========================-=========================================================================================
ii  libusb-0.1-4:amd64                         2:0.1.12-31                amd64                      userspace USB programming library
ii  libusb-1.0-0:amd64                         2:1.0.21-2                 amd64                      userspace USB programming library
ii  libusb-dev                                 2:0.1.12-31                amd64                      userspace USB programming library development files
un  libusbmuxd-tools                           <none>                     <none>                     (no description available)
ii  libusbmuxd4:amd64                          1.1.0~git20171206.c724e70f amd64                      USB multiplexor daemon for iPhone and iPod Touch devices - library
ii  libusbredirhost1:amd64                     0.7.1-1                    amd64                      Implementing the usb-host (*) side of a usbredir connection (runtime)
ii  libusbredirparser1:amd64                   0.7.1-1                    amd64                      Parser for the usbredir protocol (runtime)
```
but we encounter this error with

```
$ dpkg -l libusb*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name Version Architecture Description
+++-========================-===========================-============-=====================================================================
ii libusb-0.1-4:amd64 2:0.1.12-32 amd64 userspace USB programming library
ii libusb-1.0-0:amd64 2:1.0.22-2 amd64 userspace USB programming library
ii libusb-1.0-0-dev:amd64 2:1.0.22-2 amd64 userspace USB programming library development files
ii libusb-1.0-doc 2:1.0.22-2 all documentation for userspace USB programming
ii libusb-dev 2:0.1.12-32 amd64 userspace USB programming library development files
ii libusbmuxd4:amd64 1.1.0~git20181007.07a493a-1 amd64 USB multiplexor daemon for iPhone and iPod Touch devices - library
ii libusbredirhost1:amd64 0.8.0-1 amd64 Implementing the usb-host (*) side of a usbredir connection (runtime)
ii libusbredirparser1:amd64 0.8.0-1 amd64 Parser for the usbredir protocol (runtime)
```

**Comment by solonfan** [comment]
@tammerOfTheGods 

solon@solon-Precision-WorkStation-T5500:~$ dpkg -l libusb
libusb-0.1-4                 libusbmuxd4
libusb-1.0-0                 libusbmuxd-dev
libusb-1.0-0-dev             libusbmuxd-tools
libusb-1.0-doc               libusb-ocaml
libusbauth-configparser1     libusb-ocaml-dev
libusbauth-configparser-dev  libusbprog0v5
libusb-dev                   libusbprog-dev
libusbguard0                 libusbredirhost1
libusbhid-common             libusbredirhost-dev
libusb-java                  libusbredirparser1
libusb-java-dbg              libusbredirparser-dev
libusb-java-doc              libusbtc08-1
libusb-java-lib              libusbtc08-dev
libusbmuxd2                  

Thanks,
SolonFan

**Comment by muthuselvamr** [comment]
I am getting below output for dpkg -l libusb*

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                          Version                     Architecture                Description
+++-=============================================-===========================-===========================-================================================================================================
ii  libusb-0.1-4:amd64                            2:0.1.12-31                 amd64                       userspace USB programming library
ii  libusb-1.0-0:amd64                            2:1.0.21-2                  amd64                       userspace USB programming library
ii  libusb-1.0-0-dev:amd64                        2:1.0.21-2                  amd64                       userspace USB programming library development files
un  libusb-1.0-doc                                <none>                      <none>                      (no description available)
ii  libusb-dev                                    2:0.1.12-31                 amd64                       userspace USB programming library development files
un  libusbmuxd-tools                              <none>                      <none>                      (no description available)
ii  libusbmuxd4:amd64                             1.1.0~git20171206.c724e70f- amd64                       USB multiplexor daemon for iPhone and iPod Touch devices - library

**Comment by tammerOfTheGods** [comment]
Looks like my libusb versions are similar to @muthuselvamr and the problem is specific to SF600s. Dediprog has provided an update to correct this problem see https://github.com/DediProgSW/SF100Linux/issues/39

**Comment by muthuselvamr** [comment]
Perfect ! The latest code works well with latest code (Commit: b99e9db6352f85a446e274b284ab4beb4da34973)

Thank You all.
