### ISSUE TITLE
Lots of build warnings

### ISSUE THREAD

**Issue by j-f-d** [DediProgSW/SF100Linux#4]
Compiling on Ubuntu 16.04 LTS with:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2)

I get the attached warnings.
[make.txt](https://github.com/DediProgSW/SF100Linux/files/606792/make.txt)

**Comment by DediprogEvy** [comment]
The warnings has been fixed. Thank you.
