### ISSUE TITLE
dpcmd not working since commit e556c12c83c296493a7c224b0dd7a33c4e6036ea

### ISSUE THREAD

**Issue by martin-rufilla** [DediProgSW/SF100Linux#40]
The dpcmd has stopped working on my Ubuntu 20.04 machine since the following commit
commit e556c12c83c296493a7c224b0dd7a33c4e6036ea (HEAD)
Author: Stefan Reinauer <stefan.reinauer@coreboot.org>
Date:   Fri Nov 20 16:12:32 2020 -0800

    Migrate dpcmd to libusb-1.0
    
    The USB code in usbdriver.c was originally written for the now
    unsupported libusb-0.1 library. Port to the newer API of libusb-1.0
    to make it easier to compile for newer Linux distributions.
    
    Signed-off-by: Stefan Reinauer <stefan.reinauer@coreboot.org>

The symptoms are that the first command works and then it fails to even detect the device thereafter.
Here's an example where it the verify fails because it can't detect the flash device.  Any subsequent command fails with the same error until I power reset the DediProg.  It's a DediProg SF100

sudo dpcmd --auto ./factory.bin --addr 0x80000 --verify

DpCmd Linux 1.11.2.01 Engine Version:
Last Built on May 25 2018

 
Control Pipe input error!
By reading the chip ID, the chip applies to [ MX66L51235F ]
MX66L51235F parameters to be applied by default
MX66L51235F chip size is 67108864 bytes.

Loading file, please wait ...(./factory.bin)
Auto Sequences, please wait ...
0.6s elapsed

Device 1 (DP115332):
Automatic program OK

Checksum(whole file): 01AB8FCE
Checksum(Written part of file): 01AB8FCE

Verifying, please wait ...
0.1s elapsedWarning: Failed to detect flash (0).

Device 1 (DP115332):
Error: Verify Failed

**Comment by DediprogEvy** [comment]
Hi,

Software has been updated. Now version is DpCmd 1.11.4.x. Please update the code and help to check if still have problem. We will double check this issue and let you know the result. 
Thank you. 

BR,
DediProg Evy.

**Comment by martin-rufilla** [comment]
Hi,

I can confirm that the latest version compiled from the git repository does now work.


Kind regards

Martin



Martin Townsend | Embedded Software Engineer

martin@rufilla.com<mailto:martin@rufilla.com>


W  http://www.rufilla.com<http://www.rufilla.com/>

T    +44 (0)1865 601201

A    Building D5 | Culham Science Centre | Abingdon, UK | OX14 3DB



[rufilla_logo_transparent]<http://www.rufilla.com/>



Rufilla Ltd is a company registered in England and Wales, No. 7093478.  Registered address : 6a St Andrew’s Court, Wellington Street, Thame, Oxfordshire, OX9 3WT, United Kingdom.  Rufilla Ltd cannot guarantee e-mail transmission to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept any liability whatsoever for any errors or omissions in the contents of this message or that arises from any data corruption, interception or unauthorised amendment, whether or not these arise as a result of the e-mail transmission. The information on which this communication is based has been obtained from sources we believe to be reliable, but we do not guarantee its accuracy or completeness. All expressions of opinion are subject to change without notice.  This email may contain confidential information and as such, should be treated as confidential. It may also contain legally privileged information. It is intended solely for use by the normal or ordinary user of the e-mail address to which it has been addressed. If you are not the named addressee of this e-mail you are prohibited from disseminating, distributing, amending, copying or otherwise acting on the contents, including any attachments, of this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail in error and immediately delete this e-mail from your system. You may be asked to confirm that the e-mail received in error has been deleted from your system and/or that you have not made any unauthorised use, disclosure, distribution or copy of the e-mail. Rufilla Ltd is a VAT registered company No.131363252.



Any and all communications sent to us may be monitored and/or stored by us to ensure compliance with relevant legislation, rules, and policies.  All communications are handled in full compliance with current data protection legislation including, but not limited to, EU Regulation 2016/679 General Data Protection Regulation (“GDPR”).  For further information, please refer to our Privacy Policy<http://www.rufilla.com/s/wp-content/uploads/2018/06/GDPR_Privacy_Notice_20180615-FINAL.pdf>



<http://www.rufilla.com/site/wp-content/uploads/2018/06/GDPR_Privacy_Notice_20180615-FINAL.pdf>


________________________________

**Comment by DediprogEvy** [comment]
Hi Martin,

Thanks for your reply. It's good to know the work well.

BR,
DediProg Evy
