### ISSUE TITLE
SF100 erase chip 

### ISSUE THREAD

**Issue by gluhow** [DediProgSW/SF100Linux#43]
I have MT25QL512A and SF100.
I run from UBUNTU 21.10

```
./dpcmd -e

DpCmd Linux 1.12.7.05 Engine Version:
Last Built on October 27 2021

 
By reading the chip ID, the chip applies to [  N25Q512A13 N25Q512A83 MT25QL512A(Secure) MT25QL512A MT25QL512ABA8ESFE01-2SIT MT25TL512B MT25TL512H MT25TL01GB MT25TL01GB ]

N25Q512A13 parameters to be applied by default
N25Q512A13 chip size is 67108864 bytes.


Erasing, please wait ... 

Device 1 (DP118406):
0.7s elapsed

Device 1 (DP118406):
Erase OK
```

**0.7s**!

```
./dpcmd -b

DpCmd Linux 1.12.7.05 Engine Version:
Last Built on October 27 2021

 
By reading the chip ID, the chip applies to [  N25Q512A13 N25Q512A83 MT25QL512A(Secure) MT25QL512A MT25QL512ABA8ESFE01-2SIT MT25TL512B MT25TL512H MT25TL01GB MT25TL01GB ]

N25Q512A13 parameters to be applied by default
N25Q512A13 chip size is 67108864 bytes.


Checking, please wait ...

Device 1 (DP118406):
100.1s elapsed

Device 1 (DP118406):
The chip is NOT blank
```

**Comment by DediprogEvy** [comment]
Hi Glukhov,

I've tried, but the issue cannot be duplicated. Could you please let me know the following the detail?
1. Chip Type (if user not use "type" command, the first chip always be selected)
2. Connection way (ICP, BBF or Bottom Board + Socket Adaptor...)?
3. Cable length? (We recommend the length is 5cm)

Thanks 
Evy,
DediProg

**Comment by gluhow** [comment]
Hi
1. I use chip MT25QL512ABB1EW9-0SIT.

```
./dpcmd -d

DpCmd Linux 1.12.7.05 Engine Version:
Last Built on October 27 2021

 

Device 1 (DP118406):	detecting chip
By reading the chip ID, the chip applies to [  N25Q512A13 N25Q512A83 MT25QL512A(Secure) MT25QL512A MT25QL512ABA8ESFE01-2SIT MT25TL512B MT25TL512H MT25TL01GB MT25TL01GB ]
N25Q512A13 chip size is 67108864 bytes.
```
 2. I don't know [Connect pic](https://disk.yandex.ru/i/HjCDO9wZizuF-Q). SF100 - cable - board header
 3. I am using a factory-supplied 5cm cable

If the chip is already clean (I use `flashrom -p dediprog -c MT25QL512 -E`), then the write operation ` dpcmd -uFILE` is correct

**Comment by DediprogEvy** [comment]
Hi Glukhov,

MT25QL512ABB was not supported, I've add the chip part number, MT25QL512ABB, in the data base. 
when programming without using --type command, the first chip always be selected.  
N25Q512A13 is stacked device (two 256Mb die), and there are differences chip erase command between these two chips.
Thanks.
 
Evy,
DediProg

**Comment by gluhow** [comment]
It works. Thank you
