### ISSUE TITLE
Ignore my filename

### ISSUE THREAD

**Issue by gluhow** [DediProgSW/SF100Linux#46]
Dear Evy, the problem has changed but not resolved

```
 ~/projects/SF100Linux/dpcmd -r ~/bin/boot_flash

DpCmd Linux 1.12.8.05 Engine Version:
Last Built on October 27 2021

 
By reading the chip ID, the chip applies to [  N25Q512A13 N25Q512A83 MT25QL512A(Secure) MT25QL512A MT25QL512ABA8ESFE01-2SIT MT25TL512B MT25TL512H MT25TL01GB MT25TL01GB ]

N25Q512A13 parameters to be applied by default
N25Q512A13 chip size is 67108864 bytes.


Reading, please wait ...

Device 1 (DP118406):
100.2s elapsed

Device 1 (DP118406):
Read OK

Successfully saved into file:_1
```

_Originally posted by @gluhow in https://github.com/DediProgSW/SF100Linux/issues/44#issuecomment-994764256_

**Comment by DediprogEvy** [comment]
Dear Glukhov,
 
Sorry for I not double checked after code fixed.
Please download new code. 
Thanks.

Evy

**Comment by gluhow** [comment]
```
~/projects/SF100Linux/dpcmd -r ~/bin/boot.bin --type MT25QL512ABB

DpCmd Linux 1.12.9.06 Engine Version:
Last Built on October 27 2021

Chip Type MT25QL512ABB is applied manually.
MT25QL512ABB chip size is 67108864 bytes.


Reading, please wait ...

Device 1 (DP118406):
97.7s elapsed

Device 1 (DP118406):
Read OK

Successfully saved into file:/home/glukhov/bin/boot_1.bin
```

Funny. It's still not the same path, but at least in the right directory

**Comment by DediprogEvy** [comment]
Hi Glukhov,

Because "~" points to your $HOME. So in source code, the parameter which is followed read command, the real path, will show on the terminal screen. 
Thanks.

Evy,
DediProg

**Comment by gluhow** [comment]
I try write boot.bin, dpcmd writed boot_1.bin!

**Comment by DediprogEvy** [comment]
Hi Glukhov,

Please let me explain. "_1" means device 1. Dpcmd can connect more than one devices to program. So we add "_n" to identify the file path is the device n read file.
Thanks.

Evy,
DediProg

**Comment by gluhow** [comment]
I think that if there are more than 1 devices, then you need to ask which device you need to work with, but keep the name that the user sets. In any case, adding _1 at the end of the file bothers me much less than at the beginning. Thank you

**Comment by DediprogEvy** [comment]
Hi Glukhov,

**Comment by DediprogEvy** [comment]
Hi Glukhov,

You are right. I'll fix the code, and let you know if update. 
Thanks for your advice.

Evy,
DediProg

**Comment by DediprogEvy** [comment]
Hi Glukhov,

I fixed the code and also double check the issue. If only one device connected, then there's no "_1" follow path. 
Thanks.

Evy,
DediProg

**Comment by gluhow** [comment]
Everything is working. Thank you
