### ISSUE TITLE
Firmware update of SF600

### ISSUE THREAD

**Issue by jan-kiszka** [DediProgSW/SF100Linux#49]
I was trying to update the firmware on my SF600 using the latest 7.3.07 version from https://www.dediprog.com/product/SF600 - was this ever tested on Linux?
```
diff --git a/dpcmd.c b/dpcmd.c
index 650e372..97476b9 100755
--- a/dpcmd.c
+++ b/dpcmd.c
@@ -919,7 +919,8 @@ int FirmwareUpdate()
     }
 
     // obtain file size:
-    filesize = fseek(pFile, 0, SEEK_END);
+    fseek(pFile, 0, SEEK_END);
+    filesize = ftell(pFile);
     if (filesize < sizeof(FW_INFO)) {
         printf("File %s too small.\n", g_parameter_fw);
         return -1;
```
With this fixed, I'm now facing
```
$ ./dpcmd -U ~/SF600_V7_3_07_F1020.dpfw 

DpCmd Linux 1.12.9.06 Engine Version:
Last Built on October 27 2021

 
Current Firmware is 70202, New Firmware Version is 70307
Error: This firmware for SF600PLUS!
Error: This firmware can not be updated on this programmer!
```
Is this a real incompatibility of the offered firmware with my non-PLUS device or just an issue of the compatibility check? I don't what to risk bricking the device by skipping the test.

The reason for the update attempt is some instability in communication with USB host: If it undergoes a reboot, the device will not reaction on USB transaction. Only re-plugging it resolves the issue then. This is bad for remote operation which I'm trying to set up.

**Comment by DediprogEvy** [comment]
Hi Jan Kiszka,

Please re-download the firmware. Actually whether SF600 or SF600Plus firmware all are used in common.
Thanks.

Best Regards,
DediProg,
Evy

**Comment by jan-kiszka** [comment]
I'm I right that you fixed up the firmware image on the server? This is the diff between the version I downloaded yesterday and just now:

```
--- /dev/fd/63  2022-02-14 08:34:20.062256259 +0100
+++ /dev/fd/62  2022-02-14 08:34:20.062256259 +0100
@@ -1,4 +1,4 @@
-00000000  53 46 36 30 30 50 4c 55  53 00 00 00 00 00 00 00  |SF600PLUS.......|
+00000000  53 46 36 30 30 00 00 00  00 00 00 00 00 00 00 00  |SF600...........|
 00000010  00 00 00 00 37 2e 33 2e  30 37 00 00 00 00 31 30  |....7.3.07....10|
 00000020  32 30 00 00 00 00 00 00  57 46 50 44 00 00 00 00  |20......WFPD....|
 00000030  00 00 00 00 00 00 00 00  00 01 00 00 9c 66 01 00  |.............f..|
```

Update worked now for me. Hope that this will not make all the SF600PLUS users now unhappy...

Anyway, the code remains broken /wrt filesize. Will you fix it, or do you need a PR?

**Comment by jan-kiszka** [comment]
Ah, fixed by 517ecb51cb6457db44ab072cf56c3b8c88a9c2f5. Github knows a nice feature: If you add "Fixes #issue-no" to the commit message, a reference is automatically established.

**Comment by DediprogEvy** [comment]
Hi,

Thanks for your feedback.

**Comment by jan-kiszka** [comment]
And even more good news: The firmware update seems to have resolved the USB device issues. I can now operate it via a RPi4, remotely. Nice!

**Comment by DediprogEvy** [comment]
Good!
