### ISSUE TITLE
SF100 1.8V for low power MT25QU256ABA

### ISSUE THREAD

**Issue by Yury0707** [DediProgSW/SF100Linux#51]
~~WTF IS GOING ON?!?!~~ Hello, dear friends!

I'm using DEDIPROG SF100 and I've ~~burned already 2 motherboards~~ got some troubles with switching to 1.8V for my MT25QU256ABA. It is a low power SPI Flash chip, and it is in the “ChipInfoDb.dedicfg” with the right value for voltage (1.8 V). But the programmer uses 3.5 V while detection and during communication with it. I’ve already tried explicitly add “-c  MT25QU256ABA” and even used “--vcc 2” which stands for 1.8 V mode. But unfortunately I’ve got the same result (3.5 V of output). I’ve even tried to hard-code “unsigned int g_Vcc = vcc1_8V;” but it didn’t help either. 

The programmer’s firmware is the latest  (6.5.03).

Windows flash program detects chip right and uses right voltage (checked with oscilloscope).

Hope this information will be helpful for somebody.

**Comment by DediprogEvy** [comment]
Hi,
Sorry for delay reply.
SF100 cannot fine-tune the voltage, once the chip has Power consumption, then SF100 may not recognized the chip. 
Please try to add external power to provide power to chip. 
Thanks.
