### ISSUE TITLE
It is very slow comparing to the Windows GUI version.

### ISSUE THREAD

**Issue by adlinktech-philxing** [DediProgSW/SF100Linux#52]
Sometime it is 500 seconds(Win GUI) to 50 seconds(Linux), is it possible to align with the fast one?

**Comment by DediprogEvy** [comment]
Hi,
Please providing the following details for duplicate,
1. Chip name
2. Programmer information (programmer, firmware ver., software ver.,...)
3. Programming way( ICP, socket, ...)

Thanks.

**Comment by PhilXing** [comment]
Hi Evy,

For question 1 and 2:
[image: image.png]

for question 3: (I am not sure what is the way)
[image: image.png]

Evy liu ***@***.***> 於 2022年11月15日 週二 下午4:32寫道：

**Comment by DediprogEvy** [comment]
Hi, 
I cannot see the pictures, maybe you may send the pictures to my mail.
"evy.liu@dediprog.com" is my e-mail address.

Thanks.
Evy.

**Comment by DediprogEvy** [comment]
Hi, 

Please set the batch setting (Config - > Batch) with item 1 or item 2. Thanks.

**Comment by DediprogEvy** [comment]
Hi Phil,

 

I’ve tried but couldn’t duplicate the issue. Please refer to the following pictures. 

For 8Mbyte, erase is 17.9s, program is 64.9s  and verify is 32.8s. 

For 16Mbyte, erase is 17.9s, program is 126.2s  and verify is 64.5s. 

 

Others,

For 16Mbyte, If use “batch” command, batch: 208.2s s

For 8Mbyte, if use “auto” command , batch:159.9s

For 16Mbyte, if use “auto” command, batch: 316.7s

 

Did you used “auto” command? “--auto” command is usually used for part of data would be update, if  the image would like to be changed, we recommend to use “-e -p file -v” or “-z file -v” to reduce time.

 

Thanks.

 

Command: “./dpcmd --type S25FL128K -e -p 8Mbyte file -v”



Command: “./dpcmd --type S25FL128K -e -p 16Mbyte file -v”



 

Command: “./dpcmd --type S25FL128K -z 16Mbyte file -v”



 

Yours sincerely,

Evy Liu | Software Engineer

DediProg
