### ISSUE TITLE
Linux SF100 does not detect GigaDevice GD25LB256E

### ISSUE THREAD

**Issue by leettatt** [DediProgSW/SF100Linux#53]
Linux SF100 does not detect GigaDevice GD25LB256E chip, but Windows program can detect. Please help to update linux program.

DpCmd Linux 1.12.10.06 Engine Version:
Last Built on October 27 2021

Device 1 (SF619853):    detecting chip
Error: chip not identified.

**Comment by leettatt** [comment]
May I know whether changes on below are required to support the "GD25LB256E" chip? 
![image](https://user-images.githubusercontent.com/105268063/201142713-687a59c7-6695-41bf-9238-14dbda524314.png)

**Comment by DediprogEvy** [comment]
Hi,
It's sorry for delay reply. I will modify the chip configuration this week as soon as possible.
Thanks.

**Comment by leettatt** [comment]
Thanks. I did attempt the above changes on the ChipInfoDb.dedicfg file , but it complain on "Verify Fail".
I not sure whether issue related to my setup or miss out some other changes. Appreciate your support to make it work on SF100Linux. Thanks.
![image](https://user-images.githubusercontent.com/105268063/201805769-13c8e7d1-27b4-4530-b197-62bf0b90bc54.png)

**Comment by DediprogEvy** [comment]
Hi, 

I've fixed the issue, please update the code. Thanks.

**Comment by leettatt** [comment]
Thanks working fine now :)
