### ISSUE TITLE
Add support for GD25LQ16E

### ISSUE THREAD

**Issue by aurabindo** [DediProgSW/SF100Linux#55]
Product website: https://www.gigadevice.com/flash-memory/gd25lq16e/
Datasheet: https://www.gigadevice.com/datasheet/gd25lq16e/

**Comment by DediprogEvy** [comment]
Hi Aurabindo,

GD25LQ16E already supported. 
If there's any issue, please feel free to let us know.
Thanks.

BR,
Evy.
