### ISSUE TITLE
W77Q128JWSIQ is not supported in linux version

### ISSUE THREAD

**Issue by anthonytian2023** [DediProgSW/SF100Linux#57]
W77Q128JWSIQ is not in the list of Linux dpcmd. But it is supported in Windows version.
Could you please help to add it to Linux version?

**Comment by DediprogEvy** [comment]
OK, I will support the chip and let you know. Thanks.

**Comment by DediprogEvy** [comment]
Hi Anthony, 

Sorry for late support. W77Q128JW has been supported and work well. 
If there's any issue, please let us know. 
Thanks.

BR,
Evy.
