### ISSUE TITLE
Feature Request: write status register

### ISSUE THREAD

**Issue by jarviwan** [DediProgSW/SF100Linux#60]
Hi DediProg Linux developers @DediprogEvy ,

We saw the windows GUI version has this write status register function and we found this is super useful when a bad firmware binary got flashed into a board and write protection is thus triggered for the ROM. Basically we can use this function to unlock the protection and overwrite the binary stored in the ROM.
![image](https://user-images.githubusercontent.com/110935189/224073327-7ea2a450-8040-4e09-bd9f-f85946b4a9e5.png)

Do we have something similar in the linux cmdline tool or if not, could we have one?

Thanks,
Jarvis

**Comment by DediprogEvy** [comment]
Hi Jarvis,

Please use "--raw-instruction" and "--raw-require-return" commands to replace "write flash" feature. This two functions is like with Engineering Mode feature.
For example, 
                   --raw-instruction 06
                   --raw-instruction 01 00
                   --raw-instruction 05 --raw-require-return 1  (for getting value of status register)
 
Thanks.
Evy
