### ISSUE TITLE
dpcmd --read is inserting 00 bytes

### ISSUE THREAD

**Issue by ozpaulb** [DediProgSW/SF100Linux#61]
Hello -

using "dpcmd --read filename.bin" to read the contents of an SPI flash chip, I'm finding that extra '00' bytes are inserted.

for example, the expected image starts:

```
00000000  7f 45 4c 46 01 01 01 00  00 00 00 00 00 00 00 00  |.ELF............|
00000010  02 00 28 00 01 00 00 00  90 14 8c 0a 34 00 00 00  |..(.........4...|

```
but the result from "dpcmd --read" starts:

```
00000000  00 7f 45 4c 46 01 01 01  00 00 00 00 00 00 00 00  |..ELF...........|
00000010  00 02 00 28 00 01 00 00  00 90 14 8c 0a 34 00 00  |...(.........4..|

```
(note the leading '00' - there are others interspersed in the image too)

using the "flashrom" utility ("flashrom -p dediprog -c W25Q256FV --read filename.bin"), I don't see this issue

it seems consistent (so far) that "dpcmd" has this issue, but "flashrom" does not.

I've tried lowering the SPI clock rate from default 12MHz to 3MHz - same result

I've looked through the dpcmd options, and can't find anything obvious to try.

do you have any suggestions?

thanks!

**Comment by ozpaulb** [comment]
Update: I fixed this by swapping these two "ifs" in project.c:

```
    } else if (strstr(Chip_Info.Class, SUPPORT_WINBOND_W25Pxx) != NULL) {

        mcode_RDSR = RDSR;
        mcode_WRSR = WRSR;
        mcode_ChipErase = CHIP_ERASE;
        mcode_Program = PAGE_PROGRAM;
        mcode_Read = BULK_FAST_READ;
        mcode_SegmentErase = SE;
        mcode_ProgramCode_4Adr = 0x02;
        mcode_ReadCode = 0x0B; 
    } else if (strstr(Chip_Info.Class, SUPPORT_WINBOND_W25Pxx_Large) != NULL) {
        mcode_RDSR = RDSR;
        mcode_WRSR = WRSR;
        mcode_ChipErase = CHIP_ERASE;
        mcode_Program = PP_4ADR_256BYTE;
        mcode_Read = BULK_4BYTE_FAST_READ;
        mcode_SegmentErase = SE;
        mcode_ProgramCode_4Adr = 0x02;
        mcode_ReadCode = 0x0C;

```

the chip I'm using (W25Q256FV) has class "W25Pxx_Large".  because the first strstr() with SUPPORT_WINBOND_W25Pxx matches that in a substring match, it never gets to the second strstr() with SUPPORT_WINBOND_W25Pxx_Large.

as I said, swapping the "ifs" fixes it (it now reads valid data without injecting bogus '00' bytes)

**Comment by ozpaulb** [comment]
i'm not sure I should have 'closed' this, as it's still an issue in the code (I only have a local patch)

feel free to close/delete if you like

**Comment by DediprogEvy** [comment]
I'll close this issue.

Sorry for ignored this issue. If still have any problem in using. Please feel free to let us know.
Thanks.

Best Regards,
Evy
