### ISSUE TITLE
Control Pipe input error happens

### ISSUE THREAD

**Issue by anthonytian2023** [DediProgSW/SF100Linux#65]
When using dpcmd command with the latest code, get below error.
![image](https://github.com/DediProgSW/SF100Linux/assets/124351484/337b650c-fa46-41d7-bb80-808b73031157)

But after git reset the code to drop some patches, there is no such issue.

**Comment by DediprogEvy** [comment]
Hi,
Now the DpCmd Linux version is1.14.12.08. Could you please try to check if still have any issue on latest version? if still have issue, please let us know the programmer type and the firmware version. Thanks.

Best Regards,
Evy.
