### ISSUE TITLE
Linux SF100 does not detect GigaDevice GD25LR512ME chip

### ISSUE THREAD

**Issue by Clargent** [DediProgSW/SF100Linux#66]
Linux SF100 does not detect GigaDevice GD25LR512ME chip, but Windows program can detect. Please help to update linux program.
![image](https://github.com/DediProgSW/SF100Linux/assets/140521934/cfcbab0b-4615-4454-8f92-ed601463bb31)
![8bddc6e5-c7c4-4e5b-9220-6584ff5a4fc3](https://github.com/DediProgSW/SF100Linux/assets/140521934/35d5fdb2-945c-4ce0-981c-7df2b48f64b2)

**Comment by DediprogEvy** [comment]
Hi,

sorry for late reply.
ChipInfoDb.dedicfg has been update.
I've tried to program the chip and work well.

Thanks.
Best Regards,
Evy.
