### ISSUE TITLE
timestub error

### ISSUE THREAD

**Issue by kmakhil90** [DediProgSW/SF100Linux#8]
Found a compile error related linker "undefined reference to timestub". Anybody can suggest solutions.

**Comment by DediprogEvy** [comment]
Please provide the firmware version of the programmer, chip part number and using command for duplicate the issue. Thank you.

**Comment by DediprogEvy** [comment]
Please let us know the Linux version you are using. Thank you.

**Comment by DediprogEvy** [comment]
Please let me know the chip part number, firmware version. Thank you.

**Comment by kmakhil90** [comment]
chip is W25Q32 and the firmware version 5.5.01(SF100).

**Comment by DediprogEvy** [comment]
We've discussed on the mail, so i close this issue. Thank you.
