### ISSUE TITLE
Ubuntu 16.04.3 compile errors

### ISSUE THREAD

**Issue by rcpao** [DediProgSW/SF100Linux#9]
Ubuntu 16.04.3

$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make
gcc -Os -Wall -lpthread    -c -o dpcmd.o dpcmd.c
In file included from dpcmd.c:7:0:
usbdriver.h:7:17: fatal error: usb.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'dpcmd.o' failed
make: *** [dpcmd.o] Error 1

Replace #include <usb.h> with #include <libusb-1.0/libusb.h> results in the following:

$ make
gcc -Os -Wall -lpthread    -c -o dpcmd.o dpcmd.c
In file included from dpcmd.c:7:0:
usbdriver.h:33:23: error: field ‘usb_device_handler’ has incomplete type
     struct usb_device usb_device_handler;
                       ^
dpcmd.c: In function ‘GetConfigVer’:
dpcmd.c:476:10: warning: implicit declaration of function ‘strtol’ [-Wimplicit-function-declaration]
    Ver = strtol(tok,NULL,10);
          ^
dpcmd.c: In function ‘ExitProgram’:
dpcmd.c:741:13: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
             free(pBufferForLastReadData[i]); 
             ^
dpcmd.c:741:13: warning: incompatible implicit declaration of built-in function ‘free’
dpcmd.c:741:13: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’
dpcmd.c:745:10: warning: incompatible implicit declaration of built-in function ‘free’
          free(pBufferforLoadedFile);
          ^
dpcmd.c:745:10: note: include ‘<stdlib.h>’ or provide a declaration of ‘free’
dpcmd.c: In function ‘sin_handler’:
dpcmd.c:951:17: warning: unused variable ‘basetv’ [-Wunused-variable]
  struct timeval basetv[3];
                 ^
dpcmd.c: In function ‘Handler’:
dpcmd.c:961:8: warning: implicit declaration of function ‘Is_usbworking’ [-Wimplicit-function-declaration]
     if(Is_usbworking(0)==true)
        ^
dpcmd.c: In function ‘ListTypes’:
dpcmd.c:1219:2: warning: implicit declaration of function ‘Dedi_List_AllChip’ [-Wimplicit-function-declaration]
  Dedi_List_AllChip();
  ^
dpcmd.c: In function ‘Read’:
dpcmd.c:1519:9: warning: unused variable ‘dev_cnt’ [-Wunused-variable]
     int dev_cnt=get_usb_dev_cnt();
         ^
dpcmd.c: In function ‘CalChecksum’:
dpcmd.c:1569:14: warning: format ‘%zX’ expects argument of type ‘size_t’, but argument 2 has type ‘unsigned int’ [-Wformat=]
       printf("Checksum of the whole chip(address starting from: 0x%zX, 0x%X byt
              ^
dpcmd.c:1569:14: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
dpcmd.c:1592:17: warning: format ‘%zX’ expects argument of type ‘size_t’, but argument 2 has type ‘unsigned int’ [-Wformat=]
          printf("Checksum of the whole chip(address starting from: 0x%zX, 0x%X 
                 ^
dpcmd.c:1592:17: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘size_t {aka long unsigned int}’ [-Wformat=]
dpcmd.c: In function ‘FlashIdentifier’:
dpcmd.c:1678:14: warning: implicit declaration of function ‘Dedi_Search_Chip_Db’ [-Wimplicit-function-declaration]
         rc = Dedi_Search_Chip_Db(0x9f, UniqueID, Chip_Info, search_all,Index);
              ^
<builtin>: recipe for target 'dpcmd.o' failed
make: *** [dpcmd.o] Error 1

**Comment by DediprogEvy** [comment]
Could you please help to check if the file exist in the folder same as make file?

**Comment by AndreyShamis** [comment]
sudo apt install libusb-dev

**Comment by DediprogEvy** [comment]
Could you please let me know the error is still exist?

**Comment by rcpao-enmotus** [comment]
sudo apt install libusb-dev
does allow it to compile.  Now there are warning messages: 
[make.txt](https://github.com/DediProgSW/SF100Linux/files/1904743/make.txt)

**Comment by reinauer** [comment]
This happened due to using libusb-0.1 originally. Support for libusb-1.0 was merged recently, so this can be closed.

**Comment by Benwang217** [comment]
This happened due to using libusb-0.1 originally. Support for libusb-1.0 was merged recently
